; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3box]
platform = espressif32
board = esp32s3box
framework = arduino
debug_tool = esp-builtin
upload_protocol = esptool
build_flags = -DCORE_DEBUG_LEVEL=2 -I include
board_build.filesystem = littlefs
extra_scripts = pre:tools/embed_bridge_ui.py
lib_deps = 
	madhephaestus/ESP32Servo@^3.1.3
	okalachev/MAVLink@^2.0.27
monitor_speed = 115200
monitor_filters = time,log2file,esp32_exception_decoder,default
